{- 
  Each new term in the Fibonacci sequence
  is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ...
  By considering the terms in the Fibonacci sequence
  whose values do not exceed four million,
  find the sum of the even-valued terms.
  -}

import Control.Exception

limit :: Int
limit = 4 * (10 ^ 6)

evenFibSum :: Int -> Int -> Int -> Int
evenFibSum x y z
  | x > z = 0
  | x <= z && mod x 2 == 0 = x + evenFibSum y (x + y) z
  | otherwise = evenFibSum y (x + y) z

main :: IO ()
main = do
  putStr "Example: "
  print (evenFibSum 1 2 100)
  assert ((evenFibSum 1 2 100) == 44) (putStr "Passed!")
  putStr "Test Case: " 
  print (evenFibSum 1 2 limit)
